import 'package:nhtelwebsite/constants/constants.dart';

class TitleAndDescriptions {
  static List<String> getTitles() => [
        SUPERIORCOUPLETITLE,
        SUPERIORDOUBLESINGLETITLE,
        SUPERIORTRIPLECOUPLETITLE,
        SUPERIORTRIPLESINGLETITLE,
        STANDARDCOUPLETITLE,
        STANDARDDOUBLESINGLETITLE,
        STANDARDSINGLETITLE,
        WORKECONOMYTITLE
      ];

  static List<String> getDescriptions() => [
        SUPERIORCOUPLEDESC,
        SUPERIORDOUBLESINGLEDESC,
        SUPERIORTRIPLECOUPLEDESC,
        SUPERIORTRIPLESINGLEDESC,
        STANDARDCOUPLEDESC,
        STANDARDDOUBLESINGLEDESC,
        STANDARDSINGLEDESC,
        WORKECONOMYDESC
      ];
}
