import 'package:nhtelwebsite/constants/constants.dart';

class TitleAndDescriptions {
  static List<String> getTitles() => [
        SUPERIORCOUPLETITLE,
        SUPERIORDOUBLESINGLETITLE,
        SUPERIORTRIPLECOUPLETITLE,
        SUPERIORTRIPLESINGLETITLE,
        STANDARDCOUPLETITLE,
        STANDARDDOUBLESINGLETITLE,
        STANDARDSINGLETITLE,
        WORKECONOMYTITLE
      ];

  static List<String> getDescriptions() => [
        SUPERIORCOUPLEDESC,
        SUPERIORDOUBLESINGLEDESC,
        SUPERIORTRIPLECOUPLEDESC,
        SUPERIORTRIPLESINGLEDESC,
        STANDARDCOUPLEDESC,
        STANDARDDOUBLESINGLEDESC,
        STANDARDSINGLEDESC,
        WORKECONOMYDESC
      ];

  static List<String> getMobileDescriptions() => [
        SUPERIORCOUPLEDESCMOBILE,
        SUPERIORDOUBLESINGLEDESCMOBILE,
        SUPERIORTRIPLECOUPLEDESCMOBILE,
        SUPERIORTRIPLESINGLEDESCMOBILE,
        STANDARDCOUPLEDESCMOBILE,
        STANDARDDOUBLESINGLEDESCMOBILE,
        STANDARDSINGLEDESCMOBILE,
        WORKECONOMYDESCMOBILE
      ];

  static List<String> getMobileTitles() => [
        COUPLESUPERIORMOBILE,
        DOUBLESINGLESUPERIORMOBILE,
        TRIPLECOUPLESUPERIORMOBILE,
        TRIPLESINGLESUPERIORMOBILE,
        COUPLESTANDARDMOBILE,
        DOUBLESINGLESTANDARDMOBILE,
        SINGLESTANDARDMOBILE,
        WORKECONOMYMOBILE
      ];
}
